### ISSUE TITLE
肉身坦克附魔无法正常生效

### ISSUE THREAD

**Issue by Tonoseihon** [Qian-F/QFserver-Wonder#10]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

根据该附魔的描述
<img width="232" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/e41e2f39-dabb-48bb-812a-f945579a11dc">
在穿上附有该附魔的装备时自身的最大生命值将会提高
然而无论是服务器还是单机中，该附魔都无法正常生效
前：
<img width="396" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/f3513029-9e39-4c15-928b-c2f4e823cc4d">
后：
<img width="390" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/e4ce1a0f-f60b-434c-9d44-dbe90302c39f">
<img width="577" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/29ed2938-0c59-46f1-baff-dd10deae486c">

**Comment by Qian-F** [comment]
等待复查

**Comment by Qian-F** [comment]
Tank I-V: 

1.18 - Protects the user from unblockable damage sources (drowning, cacti, lava, etc.)

Chestplate Only

此附魔被重新设计，在1.18.2版本中为避免受到不可阻挡的伤害
