### ISSUE TITLE
关于croptopia中的培根配方中若使用农夫乐事中刀会异常消失的错误

### ISSUE THREAD

**Issue by Tonoseihon** [Qian-F/QFserver-Wonder#12]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

该培根配方与农夫乐事进行了联动，使得可以使用农夫乐事中的刀来替代croptopia的刀来合成
然而，如果真的使用农夫乐事的刀来合成的话，因为未知的错误
刀会直接消失而不是像croptopia的刀一样保留（这培根里怎么有刀子

**Comment by Qian-F** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/404
已有相关bug

**Comment by Qian-F** [comment]
将会通过kubejs修复

**Comment by Qian-F** [comment]
已修复 将在下版本加入
