### ISSUE TITLE
抽屉模组的堆叠导致物品复制

### ISSUE THREAD

**Issue by MonianHello** [Qian-F/QFserver-Wonder#2]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

正常来说挖掉含有物品的抽屉后，物品会被保留
![image](https://github.com/Qian-F/QFserver-Wonder/assets/50223265/28351d58-504d-49c8-8713-7f539d69e88b)
同时抽屉本身可以堆叠
![image](https://github.com/Qian-F/QFserver-Wonder/assets/50223265/9ce75f3c-113e-430f-9b9e-d68a11605a81)
玩家身上有含有物品的抽屉时，再挖掉其他抽屉时，会继续堆叠，导致物品复制

### 重现步骤

复现演示：

https://github.com/Qian-F/QFserver-Wonder/assets/50223265/815dd0f7-7aca-46d6-a6fd-2927aad6820b

**Comment by Qian-F** [comment]
oh 懂了 去看看（

**Comment by Qian-F** [comment]
https://github.com/MattiDragon/ExtendedDrawers/issues/17

曾经有过 猜测是charm的问题 在查

**Comment by Qian-F** [comment]
> https://github.com/MattiDragon/ExtendedDrawers/issues/17
> 
> 曾经有过 猜测是charm的问题 在查

不是 charm 采用二分法

**Comment by Qian-F** [comment]
和更多潜影盒Upgraded Shulkers冲突导致
bug已交: https://github.com/MattiDragon/ExtendedDrawers/issues/56

**Comment by Qian-F** [comment]
> 和更多潜影盒Upgraded Shulkers冲突导致 bug已交: [MattiDragon/ExtendedDrawers#56](https://github.com/MattiDragon/ExtendedDrawers/issues/56)
> 
> 目前措施为删除更多潜影盒模组，将在月底执行

作者已回复，为更多潜影盒代码bug导致，解决措施确定为删除此模组
