### ISSUE TITLE
通过漏斗向潜影盒内放抽屉

### ISSUE THREAD

**Issue by Tonoseihon** [Qian-F/QFserver-Wonder#4]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

抽屉mod的设定是无法将功能类似潜影盒的抽屉放入潜影盒中的
<img width="380" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/7566da55-0b4a-460d-896a-87d5685a1228">
但是通过漏斗，可以将抽屉送入潜影盒中
<img width="360" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/c81b67a7-9e7b-40b7-a49a-abbae7719c3e">
该bug与通过铜管向潜影盒内放潜影盒的bug类似，但是此bug与铜管模组无关
即已删除铜管模组仍可以复现此bug

**Comment by Qian-F** [comment]
尝试仅安装这两个mod能否复现

**Comment by Tonoseihon** [comment]
还是会（

**Comment by Qian-F** [comment]
> 还是会（

我稍后验证后会提交issue至作者仓库

**Comment by Qian-F** [comment]
> > 还是会（
> 
> 我稍后验证后会提交issue至作者仓库

已验证 为模组bug 稍后提交至模组仓库
