### ISSUE TITLE
Vinery模组的烹饪锅无法正常打开

### ISSUE THREAD

**Issue by Tonoseihon** [Qian-F/QFserver-Wonder#5]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

根据mod百科介绍
<img width="341" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/d2fbb2ee-92d5-4cbc-a9bf-603265b2e418">
<img width="685" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/754c40f3-da5b-4333-8b4e-765714520f9d">
按照相应摆放方式无法正常打开烹饪锅的UI界面
<img width="575" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/a9a126b1-ca78-43bf-a720-4d59ed7722f0">
当前使用的是1.1.4版本的Vinery模组，其功能应能正常使用，在mod百科的评论区也有相关反映，但是我重启后在单机以及服务器中仍不能打开
<img width="369" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/d0cab7af-31eb-4327-a14b-acbf991148ab">

**Comment by Qian-F** [comment]
此bug等待复查，已知的是另一个团队的fork版vinery修复了此问题

**Comment by Qian-F** [comment]
经过沟通Astral Vinery选择再补一个版本单独修复Vinery的错误（大成功！将在下版本（月底）修复
https://discord.com/channels/813762487253860373/1108354516736299079/1108771128429789186

**Comment by Qian-F** [comment]
![chrome_cuWuVrdAz1](https://github.com/Qian-F/QFserver-Wonder/assets/111696321/dde8482d-5fc4-45dd-bef1-f4b925d9623d)
修复版已发布 ，月底更新
