### ISSUE TITLE
1.1.4版本的Vinery模组中的吐司和牛奶面包是一个配方

### ISSUE THREAD

**Issue by Tonoseihon** [Qian-F/QFserver-Wonder#6]
### 检查项

- [X] **这个Bug是可复现的** 即其他玩家也可以同样触发这个Bug (可选)
- [X] **Bug的确是非游戏预期内容** 请在[MC模组百科](https://mcmod.cn/)中确认这个模组的功能
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一Bug未被提交过。

### 描述

字面意思
由于使用的是模组中自带的燃木烤箱进行合成，
无法转换合成配方
在同一模组中的吐司以及牛奶面包居然使用的同一种合成方式（
导致在游戏中使用该配方只能合成出牛奶面包
<img width="569" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/ef019f0c-5429-4c6d-b6ed-ba87c8c2b1ce">
<img width="715" alt="image" src="https://github.com/Qian-F/QFserver-Wonder/assets/99337738/43d8fc0e-22fa-4b25-a7f1-8b505a896776">
顺带一提，作者在只有1.19才有的1.2版本以后更改了配方（乐

**Comment by Qian-F** [comment]
已测试 问题仍然存在

**Comment by Qian-F** [comment]
astral团队表示不会修复这个问题，看来只能通过CrT解决了（悲

**Comment by Qian-F** [comment]
配方已修改（kubejs）
