### ISSUE TITLE
为模组Slide Show添加合成配方

### ISSUE THREAD

**Issue by MonianHello** [Qian-F/QFserver-Wonder#7]
### 检查项

- [X] **此建议不涉及模组的增删** 针对需要增删模组的建议，请前往 [新功能提案](https://github.com/Qian-F/QFserver-Wonder/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E5%8F%8D%E9%A6%88&template=feature.yml)
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一建议未被提交过。

### 内容

为模组[Slide Show](https://www.mcmod.cn/class/3878.html)添加合成配方

~~不然这模组加了也没用啊~~

**Comment by Qian-F** [comment]
配方将在以后的版本通过CraftTweaker添加

**Comment by Qian-F** [comment]
已添加，在下版本加入
