### ISSUE TITLE
添加croptopia模组中猪肉干和牛肉干的配方

### ISSUE THREAD

**Issue by Tonoseihon** [Qian-F/QFserver-Wonder#8]
### 检查项

- [X] **此建议不涉及模组的增删** 针对需要增删模组的建议，请前往 [新功能提案](https://github.com/Qian-F/QFserver-Wonder/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E5%8F%8D%E9%A6%88&template=feature.yml)
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一建议未被提交过。

### 内容

在当前版本无法合成猪肉干和牛肉干两种食物，尽管作者已经在新的版本中更新了这两种食物的配方https://github.com/Ayutac/Croptopia/blob/1.19-jerky/shared/src/main/resources/data/croptopia/advancements/recipes/beef_jerky.json
https://github.com/Ayutac/Croptopia/blob/1.19-jerky/shared/src/main/resources/data/croptopia/advancements/recipes/pork_jerky.json

**Comment by Qian-F** [comment]
核对代码后将会尝试构建/通过CraftTweaker添加配方

**Comment by Qian-F** [comment]
已添加，下版本加入配方
