### ISSUE TITLE
关于饮酒作乐（Brewin' And Chewin'）的配方问题

### ISSUE THREAD

**Issue by Tonoseihon** [Qian-F/QFserver-Wonder#9]
### 检查项

- [X] **此建议不涉及模组的增删** 针对需要增删模组的建议，请前往 [新功能提案](https://github.com/Qian-F/QFserver-Wonder/issues/new?assignees=&labels=%C2%B7+%E6%96%B0%E5%8A%9F%E8%83%BD%2C%E5%8F%8D%E9%A6%88&template=feature.yml)
- [X] 我已在 [Issues 页面](https://github.com/Qian-F/QFserver-Wonder/issues) 中搜索，确认了这一建议未被提交过。

### 内容

该mod在当前游戏内无法显示出配方，而mod百科内更是啥都没有（因为大家都能在jei直接看到配方  ：）该死的rei
想知道配方甚至得去翻源码（
希望能够解决游戏内rei无法显示类似配方问题

**Comment by Qian-F** [comment]
一番交涉后作者开始添加REI支持了（喜

**Comment by Qian-F** [comment]
![chrome_njXpheJWpO](https://github.com/Qian-F/QFserver-Wonder/assets/111696321/8f99758d-5197-4978-b8ac-c2d512b611be)
作者已更新 将在月底版本加入
